package it.polimi.sw.GC50.net.util;

public enum Request {
    JOINGAME,
    CREATEGAME,
    QUITGAME,
    GETGAME,
    GETNUMBEROFPLAYER,
    GETMODEL,
    GETSTARTERCARD,
    GETCOMMONOBJECTIVE,
    GETSECRETOBJECTIVE,
    PLACECARD,
    DRAWCARDGOLD0,
    DRAWCARDGOLD1,
    DRAWCARDGOLD2,
    DRAWRESOURCE0,
    DRAWRESOURCE1,
    DRAWRESOURCE2,
    GETTURN, GAMENOTFOUND,
}
